version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    
    networks:
      - mongo-database

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - mongo-database

  api: 
    build: ./backend
    container_name: backend-api
    ports:
      - '8080:8080'
    networks:
      - mongo-database
    depends_on:
      - mongodb

  frontend: 
    build: ./frontend
    container_name: frontend-app
    ports:
      - '3000:3000'
    depends_on:
      - api


networks:
  mongo-database:
    driver: bridge
